require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'

end

target 'App' do
  capacitor_pods
  # Dynamsoft Capture Vision native SDK for iOS (native camera + capture pipeline)
  pod 'DynamsoftCaptureVisionBundle', '3.6.2000'
  pod 'DynamsoftCameraEnhancer', '4.2.24'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
