plugins {
    id 'com.android.library'
}

android {
    namespace 'com.dynamsoft.dbrbundle'
    compileSdk 35

    defaultConfig {
//        applicationId "com.dynamsoft.dbrbundle"
        minSdk 30
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    api "com.dynamsoft:dynamsoftlicense:3.4.40"
    api "com.dynamsoft:dynamsoftcore:3.4.20"
    api "com.dynamsoft:dynamsoftcameraenhancer:4.2.20"
    api "com.dynamsoft:dynamsoftcapturevisionrouter:2.4.21"
    api "com.dynamsoft:dynamsoftbarcodereader:10.4.20"
    api "com.dynamsoft:dynamsoftimageprocessing:2.4.20"
    api "com.dynamsoft:dynamsoftutility:1.4.20"
}