plugins {
    id "com.android.library"
}

ext {
    releaseVersion = "2.0.1"
}

def localPublishFileExists = file('local_publish.gradle').exists()

if (localPublishFileExists) {
    apply from: 'local_publish.gradle'
}

android {
    namespace 'com.dynamsoft.mrzscannerbundle'
    compileSdk 34

    defaultConfig {
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    // api "com.dynamsoft:dynamsoftlicense:3.4.40"
    // api "com.dynamsoft:dynamsoftcore:3.4.30"
    // api "com.dynamsoft:dynamsoftcameraenhancer:4.2.22"
    // api "com.dynamsoft:dynamsoftcapturevisionrouter:2.4.30"
    // api "com.dynamsoft:dynamsoftimageprocessing:2.4.31"
    // api "com.dynamsoft:dynamsoftutility:1.4.30"
    // api "com.dynamsoft:dynamsoftlabelrecognizer:3.4.30"
    // api "com.dynamsoft:dynamsoftneuralnetwork:1.0.21"
    // api "com.dynamsoft:dynamsoftcodeparser:2.4.30"
    // api "com.dynamsoft:dynamsoftcodeparserdedicator:1.2.31"
    api "com.dynamsoft:dynamsoftcapturevisionbundle:2.6.1003"
    api 'com.dynamsoft:dynamsoftmrz:3.4.20'
    api "com.dynamsoft:dynamsoftvin:3.4.20"

    implementation 'androidx.appcompat:appcompat:1.6.1'
}